apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: G:\My Drive\Training Courses\nucamp_backend\Python\3-DevOps\week4\Kompose\kompose.exe convert
    kompose.version: 1.23.0 (bc7d9f4f)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: G:\My Drive\Training Courses\nucamp_backend\Python\3-DevOps\week4\Kompose\kompose.exe convert
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.network/nunet: "true"
        io.kompose.service: flask-app
    spec:
      containers:
        - args:
            - python
            - flask_app/app/wsgi.py
          image: zphouston86/flask_app:latest
          name: flask-app
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
